name: 'Build static sites image'

on:
  push:
    branches:
      - main

jobs:
  build_image:
    name: Build docker image
    runs-on:
      - ubuntu-latest
    permissions:
      content: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
