name: 'Build static sites image'

on:
  push:
    branches:
      - main

jobs:
  build_image:
    name: Build docker image
    runs-on:
      - ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thinc-org/thinc-roadmap:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
